### ISSUE TITLE
Uploading video 

### ISSUE THREAD

**Issue by Karayel** [cloudinary/cloudinary_npm#129]
I am working on uploading video. Here is my codes.

First try:
```
cloudinary.uploader.upload_large(videoFile,
            function(result) {console.log(result); },
            { resource_type: "video" });
```
Second try:
```
cloudinary.uploader.upload_large(videoFile,
            function(result) {console.log(result); },
            { resource_type: "auto" });
```
Thir try:
```
cloudinary.uploader.upload_large(videoFile,
            function(result) {console.log(result); },
            { resource_type: "raw" });
```

All of the code, I am getting TypeError: callback is not a function error. Is there any problem in v1_result_adapter function.

Here is the full stack trace.

```
/home/karayel/Desktop/welmio-mvc/node_modules/cloudinary/lib/utils.js:1028
          return callback(void 0, result);
                 ^

TypeError: callback is not a function
    at v1_result_adapter (/home/karayel/Desktop/welmio-mvc/node_modules/cloudinary/lib/utils.js:1028:18)
    at exports.upload_chunked_stream.chunker.on.finished_part (/home/karayel/Desktop/welmio-mvc/node_modules/cloudinary/lib/uploader.js:172:13)
    at IncomingMessage.<anonymous> (/home/karayel/Desktop/welmio-mvc/node_modules/cloudinary/lib/uploader.js:495:51)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
```

**Comment by richgieg** [comment]
Hi Karayel,

Can you please make sure you're using the latest version of Cloudinary's Node SDK and retry? Also, if error continues, can you please post the updated stack trace?

Warm regards,
Richard

**Comment by Karayel** [comment]
Hi, 

I am sure, I am using the latest version of Cloudinary's Node SDK and I try it again and still same error.

Here is the full stack trace.

/home/karayel/Desktop/welmio-mvc/node_modules/cloudinary/lib/utils.js:1029
          callback(void 0, result);
          ^

TypeError: callback is not a function
    at /home/karayel/Desktop/welmio-mvc/node_modules/cloudinary/lib/utils.js:1029:11
    at finished_part (/home/karayel/Desktop/welmio-mvc/node_modules/cloudinary/lib/uploader.js:172:13)
    at IncomingMessage.<anonymous> (/home/karayel/Desktop/welmio-mvc/node_modules/cloudinary/lib/uploader.js:495:51)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)

**Comment by richgieg** [comment]
Hi Karayel,

Thanks for verifying. When you include `cloudinary`, which of the following do you use?

1. `var cloudinary = require('cloudinary');`
2. `var cloudinary = require('cloudinary').v2;`

Warm regards,
Richard

**Comment by Karayel** [comment]
var cloudinary = require('cloudinary').v2;

**Comment by richgieg** [comment]
When using "v2" the SDK's methods follow the convention of having the callback parameter be last in the argument list. Please try this:

```
cloudinary.uploader.upload_large(videoFile,
    { resource_type: "video" },
    function(result) { console.log(result); });
```

**Comment by Karayel** [comment]
Yeah, it is uploading the video but its return undefined. 
1. How can I understand the uploading process over ? 
2. How can I access the video url ?

**Comment by richgieg** [comment]
I apologize! "v2" also observes Node's **error-first** callback convention, so the first parameter of the callback is for errors and the second parameter is for the result. Please try:

```
cloudinary.uploader.upload_large(videoFile,
	{ resource_type: 'video' },
	function(error, result) {
		if (error) {
			// handle error
		} else {
			console.log(result);
		}
	});
```

In this case, `result` should contain the data you need.

**Comment by Karayel** [comment]
Thanks
