### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by MrShakes** [cloudinary/cloudinary_npm#209]
I'm using the `cloudinary.v2.api.delete_resources_by_tag` method to delete a bunch of resources, I'm calling this method one by one, the first few times work well then in my logs I see this error:

```
(node:21429) UnhandledPromiseRejectionWarning: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/Users/ola/Desktop/Awork/cloudinary/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/Users/ola/Desktop/Awork/cloudinary/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/ola/Desktop/Awork/cloudinary/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/ola/Desktop/Awork/cloudinary/node_modules/express/lib/response.js:158:21)
    at deleteOldProducts (/Users/ola/Desktop/Awork/cloudinary/handler.js:370:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:21429) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21429) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm using version 1.11.0
Node version 8.11.2
Npm version 5.6.0

**Comment by igy** [comment]
Hi Ola,

Can you share an example of how you're using the SDK so I can see where that error is being thrown? 
Are you also seeing errors returned by Cloudinary's server or is the error coming from your code?

Thanks,
Stephen

**Comment by MrShakes** [comment]
The error was from Cloudinary node module I believe, logs provided were from my terminal however this error did not show up again.
