### ISSUE TITLE
Broken on Node 8.x

### ISSUE THREAD

**Issue by rick-rheo** [cloudinary/cloudinary_npm#225]
At the very least  Cloudinary.v2.uploader.upload   fails with 

ERROR: 12/14 16:19:18+00:00::TypeERROR: Cannot read property 'access_mode' of null

   at build_upload_params (/opt/ImageService+r_0.0.59/server/node_modules/cloudinary/lib/utils/index.js:317:26)
    at /opt/ImageService+r_0.0.59/server/node_modules/cloudinary/lib/uploader.js:41:18
    at call_api (/opt/ImageService+r_0.0.59/server/node_modules/cloudinary/lib/uploader.js:360:52)
    at Object.upload (/opt/ImageService+r_0.0.59/server/node_modules/cloudinary/lib/uploader.js:40:10)
    at Object.upload (/opt/ImageService+r_0.0.59/server/node_modules/cloudinary/lib/utils/index.js:1149:21)
    at image.persist.id (/opt/ImageService+r_0.0.59/server/serviceModules/imageServiceModule.js:308:28)
    at Immediate.setImmediate (/opt/ImageService+r_0.0.59/server/lib/utils.js:78:8)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) 

    at Immediate.setImmediate (/opt/ImageService+r_0.0.59/server/lib/utils.js:83:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Investigating its because you're using default parameters not supported but  Node 8 LTS.

exports.upload = function upload(file, callback, options = {}) {

**Comment by yakirp** [comment]
Hi 
We checked that and look likes it's ok:

```
─amir@Bill-2 ~/Development/sandbox/node8 ‹ruby-2.2.5›
╰─$ nvm use 8
Now using node v8.12.0 (npm v6.4.1)
╭─amir@Bill-2 ~/Development/sandbox/node8 ‹ruby-2.2.5›
╰─$ node --version
v8.12.0
╭─amir@Bill-2 ~/Development/sandbox/node8 ‹ruby-2.2.5›
╰─$ node
> function f(x={msg: "default value"}){
... console.log(x.msg);
... }
undefined
> f()
default value
undefined
> f({msg: "some other value"})
some other value
undefined
> f({})
undefined
undefined
> f(null)
TypeError: Cannot read property 'msg' of null
    at f (repl:2:15)
>```
```
Maybe you are passing null to the function?

**Comment by rick-rheo** [comment]
```
storageTransforms = {transformation: {format: 'jpg', width: 1280, crop: "scale"}};
Cloudinary.v2.uploader.upload(url, storageTransforms, (error, result) => {

...
```

This works fine in version 1.9.0.  Not so much in your latest version

**Comment by shirlymanor** [comment]
Can you please try:

storageTransforms = {transformation: {format: 'jpg', width: 1280, crop: "scale"}};
cloudinary.v2.uploader.upload("http://res.cloudinary.com/demo/image/upload/sample.jpg", storageTransforms, (error, result) => {console.log(result, error); });

And let us know if that works?

**Comment by rick-rheo** [comment]
There’s no difference whatsoever between that and what I’m already doing and it crashes with the above stack.

**Comment by rick-rheo** [comment]
Clarification:  I tried, while setting url = http://res.cloudinary.com/demo/image/upload/sample.jpg

**Comment by shirlymanor** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
