### ISSUE TITLE
make lodash a strict dependency

### ISSUE THREAD

**Issue by ORESoftware** [cloudinary/cloudinary_npm#228]
I get this when using NPM cloudinary module

``` js

error: "TypeError: _.include is not a function
    at ClientRequest.handle_response (C:\Users\denman\WebstormProjects\lectal_all\api\node_modules\cloudinary\lib\api.js:70:13)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)"

```

I believe it is because lodash is missing, but if I installed cloudinary, if lodash is a strict dependency of the cloudinary module, then this shouldn't happen, what's wrong here?

**Comment by tocker** [comment]
Fixed in version 1.11.0
