### ISSUE TITLE
Bug in samples/basic

### ISSUE THREAD

**Issue by mycaule** [cloudinary/cloudinary_npm#42]
[basic.js#L41](https://github.com/cloudinary/cloudinary_npm/blob/master/samples/basic/basic.js#L41) causes the above error. 

When I comment the line, the sample code runs without problem. 

```
_stream_writable.js:175
    encoding = state.defaultEncoding;
                    ^
TypeError: Cannot read property 'defaultEncoding' of undefined
    at ReadStream.Writable.write (_stream_writable.js:175:21)
    at ReadStream.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:748:14)
    at ReadStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at ReadStream.Readable.push (_stream_readable.js:130:10)
    at onread (fs.js:1568:12)
    at Object.wrapper [as oncomplete] (fs.js:459:17)
```

**Comment by zkiiito** [comment]
actually, this bug still exists in the documentation on heroku:
https://devcenter.heroku.com/articles/cloudinary#using-with-node-js
