### ISSUE TITLE
Stream Errors

### ISSUE THREAD

**Issue by mclenithan** [cloudinary/cloudinary_npm#50]
First, great job on the module!

I have been trying to kill a bug when upgrading from version 1.0.13 to 1.1.0 or anything higher.  I am working up a test and reproduction instructions right now, will post details in a few.  

Here is the initial error when trying to kill the stream:

    _stream_writable.js:344
      if (!state.ending && !state.finished)
                ^
    TypeError: Cannot read property 'ending' of undefined
        at Stream.Writable.end (_stream_writable.js:344:13)
        at Stream.emit (events.js:92:17)
        at ChildProcess.<anonymous>     (/home/mclenithan/www/soundselect/node_modules/webshot/lib/webshot.js:242:9)
        at ChildProcess.emit (events.js:98:17)
        at Process.ChildProcess._handle.onexit (child_process.js:820:12)

If this sounds obvious, stop me there, otherwise I will have a write up to follow shortly.

**Comment by TalLevAmi** [comment]
@mclenithan were you able to reproduce this on a test?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
