### ISSUE TITLE
Cloudinary service responded with HTTP Code: 500 and HTML instead of JSON

### ISSUE THREAD

**Issue by laurynas-karvelis** [cloudinary/cloudinary_npm#8]
I've noticed that if your server returns HTTP 500 status code with HTML instead of JSON your npm module exits node.js app completely!

```
undefined:1
<!DOCTYPE html>
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.res.on.error (/Users/laurynas/www/reversio/node_modules/cloudinary/lib/uploader.coffee:304:25)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1367:20)
    at CleartextStream.CryptoStream._push (tls.js:526:27)
    at SecurePair.cycle (tls.js:880:20)
    at EncryptedStream.CryptoStream.write (tls.js:267:13)
    at Socket.ondata (stream.js:38:26)
```

uploader.coffee handle_response and api.coffee call_api tries to parse JSON assuming everything will be fine.

Please add a try catch sections for JSON.parse() there in case your servers are down and responding with non-JSON.

**Comment by juanibe** [comment]
Hi, long time after, but I think I am getting the same error...

` 'Server return invalid JSON response. Status Code 404. SyntaxError: Unexpected token < in JSON at position 0',`

This happen only when uploading video, and it was working properly before, from one day to the other started to failed...any clue?

```
  private async upload(dataStream: any, options: any): Promise<any> {
        const readStream = dataStream();
        return new Promise(async (resolve, reject) => {
            const destinationPath = this.getDestinationPath();
            const saveMedia = this.saveFileToDisk(readStream, destinationPath);

            try {
                await saveMedia;
            } catch (err) {
                console.log("SAVE MEDIA IN DISK ERROR ==>", err)
                reject(err);
            }

            cloudinary.v2.uploader.upload(destinationPath, options, (err, image) => {
                console.log("destinationPath", destinationPath, options, "options");
                console.log("ERROR 3 ==>", err)
                console.log("IMAGE ===>", image)
                if (err) {
                    console.log("ERROR IN UPLOAD 2",err);
                    reject(err);
                }

                const res = {
                    url: image.secure_url,
                    publicId: image.public_id
                };
                resolve(res);
            });
        });
    }
```

 ```
 private saveFileToDisk(readStream: any, destinationPath: any): Promise<any> {
        const writeStream = fs.createWriteStream(destinationPath);
        const saveImageToDisk = new Promise(function (res, rej) {
            writeStream.on('end', () => {
                res();
            });

            writeStream.on('finish', () => {
                res();
            });

            writeStream.on('error', (err) => {
                rej();
            });
        });

        readStream.pipe(writeStream);

        return saveImageToDisk;
    }
```
