### ISSUE TITLE
Error In DB

### ISSUE THREAD

**Issue by aayush26** [cloudinary/cloudinary_npm#81]
Listening on port 9000
GET /
Unhandled rejection Error: collection name must be a String
    at Error (<anonymous>)
    at checkCollectionName (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/jugglingdb-mongodb/node_modules/mongodb/lib/utils.js:70:11)
    at new Collection (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/jugglingdb-mongodb/node_modules/mongodb/lib/collection.js:59:3)
    at MongoDB.collection (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/jugglingdb-mongodb/lib/mongodb.js:122:34)
    at MongoDB.all (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/jugglingdb-mongodb/lib/mongodb.js:252:23)
    at /home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/promised-jugglingdb/lib/model.js:567:26
    at tryCatcher (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/promised-jugglingdb/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/promised-jugglingdb/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/promised-jugglingdb/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromiseCtx (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/promised-jugglingdb/node_modules/bluebird/js/release/promise.js:583:10)
    at Async._drainQueue (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/promised-jugglingdb/node_modules/bluebird/js/release/async.js:130:12)
    at Async._drainQueues (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/promised-jugglingdb/node_modules/bluebird/js/release/async.js:135:10)
    at Async.drainQueues (/home/timekeeper/Documents/cloudinary/cloudinary_npm/samples/photo_album/node_modules/promised-jugglingdb/node_modules/bluebird/js/release/async.js:16:14)
    at process._tickCallback (node.js:415:13)

**Comment by tocker** [comment]
Confirmed. The problem is not in the Cloudinary code but rather in jugglingdb.

**Comment by tocker** [comment]
@aayush26 - thanks for reporting this! 
The issue has been fixed and will be included in the next release.
